package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'BeforeBuild'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("BeforeBuild")) {
    vcs {
        remove(RelativeId("HomeTestTiki"), "+:. => ./home-test-tiki")
        add(RelativeId("HelloWorldProject_HomeTestTiki1"), "+:. => ./home-test-tiki")
    }
}
