package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HelloWorldProject_HomeTestTiki1'
in the project with id = 'HelloWorldProject', and delete the patch script.
*/
create(RelativeId("HelloWorldProject"), GitVcsRoot({
    id("HelloWorldProject_HomeTestTiki1")
    name = "home-test-tiki (1)"
    url = "https://github.com/mrnim94/home-test-tiki"
    branch = "master"
    branchSpec = """
        +:refs/heads/*
        +:refs/tags/*
    """.trimIndent()
}))

