package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'HelloWorldProject_DockerDe'
in the project with id = 'HelloWorldProject', and delete the patch script.
*/
create(RelativeId("HelloWorldProject"), GitVcsRoot({
    id("HelloWorldProject_DockerDe")
    name = "docker-demo"
    url = "https://github.com/mrnim94/docker-demo"
    branch = "master"
    branchSpec = "+:refs/heads/*"
}))

