package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.ui.*
import jetbrains.buildServer.configs.kotlin.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'HomeTestTiki'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("HomeTestTiki")) {
    val expected = GitVcsRoot({
        id("HomeTestTiki")
        name = "home-test-tiki"
        url = "https://github.com/mrnim94/home-test-tiki"
        branch = "master"
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        branchSpec = """
            +:refs/heads/*
            +:refs/tags/*
        """.trimIndent()
        useTagsAsBranches = true
    }

}
